Tasks/task1
AndreyDonets/altexsoft-lab-2020 pull request #2
Opened 2020-08-24 19:09 UTC by AndreyDonets

2020-08-26 13:10 UTC, alex-geraschenko requested changes

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/GetEvery10Word.cs
> +    class GetEvery10Word
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/CutCharOrWorld.cs
> +    class CutCharOrWorld
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/CutText.cs
> +    class CutText
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/GetEveryWord.cs
> +    class GetEveryWord
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/ReadText.cs
> +    class ReadText
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/ReadText.cs
> +                return null;
В этом случае все методы, которые испольуют этот метод, работать перестанут

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/StartProgram.cs
> +    class StartProgram
Имя класса должно быть существительным

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/ThirdSentences.cs
> +        public static string ThirdSentence(string text)
Имя метода должно быть глаголом

2020-08-26 13:10 UTC, alex-geraschenko commented on altexsoft-lab-2020/Words.cs
> +        public static void WordsCount()
Имя метода должно быть глаголом

2020-08-26 17:00 UTC, alex-geraschenko requested changes

2020-08-26 17:00 UTC, alex-geraschenko commented on altexsoft-lab-2020/CarversHepler.cs
> +    class CarversHepler
Опечатка

2020-08-27 09:15 UTC, alex-geraschenko requested changes

2020-08-27 09:15 UTC, alex-geraschenko commented on altexsoft-lab-2020/CarversHepler.cs
> +    class CutterHepler
Вске еще опечатка. И имя файла должно совпадать с именем класса

2020-08-27 13:40 UTC, alex-geraschenko commented
А что такое `Hepler`? Я такого слова в словаре не нашел

2020-08-27 14:26 UTC, AndreyDonets commented
Гугл переводчик говорит что это помощник

2020-08-27 14:34 UTC, AndreyDonets commented
понял, поменял

2020-08-27 15:35 UTC, alex-geraschenko approved these changes
В целом уже неплохо. Можно мержить и переходить ко второму заданию

2020-08-27 16:22 UTC, merged