First try
AndreyDonets/altexsoft-lab-2020 pull request #3
Opened 2020-08-24 19:09 UTC by AndreyDonets

2020-08-26 13:11 UTC, alex-geraschenko requested changes
Второе задание не принимается без аппрува первого

2020-08-27 18:17 UTC, alex-geraschenko requested changes
1. Необходимо смержить код из `master` с первым заданием в ветку `tasks/task2`
2. Лучше переделать сохранение рецептов в одном файле, а не создавать отдельно файл для каждого рецепта
3. Все классы и методы должны быть в `PascalCase`
4. Постарайтесь реализовать шаблоны `Repository` и `UnitOfWork`

2020-08-28 11:36 UTC, serhii-shkodenko requested changes

2020-08-28 11:36 UTC, serhii-shkodenko commented on .gitignore
> +## Ignore Visual Studio temporary files, build results, and
Достаточно одного файла .gitignore на весь репозиторий.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Models/modelRecipe.cs
> +    class ModelRecipe
Называйте модели без использования префиксов `Model`. Они лежат у Вас в папке `Models`, этого достаточно, чтобы обозначить их предназначение.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/CatalogReeder.cs
> +        private static readonly string CATALOG_PATH = $"{Environment.CurrentDirectory}\\catalog.json";
В C# принято именовать константы в PascalCase. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/CatalogReeder.cs
> +    class CatalogReeder
Опечатка в имени класса. `Reader`, а не `Reeder`.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/CatalogReeder.cs
> +                Console.WriteLine(ex);
Здесь Вы неявно вызываете ToString() на объекте, а Вам нужно сообщение из исключения.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/CatalogReeder.cs
> +    class CatalogReeder
Ваш класс занимается десериализацией данных из файла, слово каталог здесь неуместным кажется.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/IngredientReeder.cs
> +    class IngredientReeder
Опечатка в имени класса. `Reader`, а не `Reeder`.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/IngredientReeder.cs
> +                Console.WriteLine(ex);
Здесь Вы неявно вызываете ToString() на объекте, а Вам нужно сообщение из исключения.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/IngredientReeder.cs
> +        private static readonly string INGREDIENTS_PATH = $"{Environment.CurrentDirectory}\\ingredients.json";
В C# принято именовать константы в PascalCase. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Reader/IngredientReeder.cs
> +    class IngredientReeder
Вы создали много файлов, которые знаимаются одной и той же работой - десериализацией данных из файла, различаются только типы. Почитайте про `Generics` (обобщения, универсальные шаблоны).

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Recipe.cs
> +    class Recipe
Название класса наталкивает на мысль, что это модель. Однако он занимается выводом сообщений в консоль. Его стоит переназвать в соответсвии с возлагаемой на него задачей.

2020-08-28 11:36 UTC, serhii-shkodenko commented on task2/Recipe.cs
> +                int n;
Эту переменную можно объявить прямо в `TryParse`.

2020-08-28 18:48 UTC, AndreyDonets commented
"4. Постарайтесь реализовать шаблоны Repository и UnitOfWork"
Пока не уверен что получится разобраться с данными шаблонами. Подскажите где найти пример работы этих шаблонов с файлами формата json

2020-08-28 19:07 UTC, alex-geraschenko commented
Пример реализации этих шаблонов вообще можно найти тут https://www.infoworld.com/article/3107186/how-to-implement-the-repository-design-pattern-in-c.html а дальше дополнить это работой с json файлами

2020-09-01 06:55 UTC, closed without merging

2020-09-01 08:40 UTC, alex-geraschenko commented
Зачем закрывать пул реквест? Ведь он еще не до конца исправлен